"""empty message

Revision ID: 6a69b834a4c2
Revises: 
Create Date: 2023-08-26 20:58:03.386141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a69b834a4c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(), nullable=False))
        batch_op.alter_column('grade',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('word')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('grade',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.drop_column('text')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
