version: '2.4'

volumes:
  wsd-vol:

services:

  pgsql:
    image: postgres:12.11
    restart: always
    volumes:
        - wsd-vol:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  flask:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - pgsql
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app



