version: '2.4'

volumes:
  wsd-vol:

services:

  pgsql:
    image: postgres:12.11
    restart: always
    volumes:
        - wsd-vol:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    env_file:
      - .env

  flask:
    command: ["sh", "-c", "gunicorn app.prod:app -b 0.0.0.0:5000"]
    container_name: "wsd_service_app"
    restart: on-failure
    build:
      context: .
      dockerfile: ./app/Dockerfile_prod
    environment:
      FLASK_APP: ./app/app.py
      FLASK_ENV: production
      STATIC_PATH: app/app/static/styles.css
    depends_on:
      - pgsql
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app